In [1]:
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [2]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [3]:
independent=dataset[["age","bmi","children","sex_male","smoker_yes"]]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [4]:
dependent=dataset[["charges"]]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [6]:
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {
    'criterion': ['squared_error', 'friedman_mse', 'absolute_error'],
    'splitter': ['best', 'random'],
    'max_features': [None, 'sqrt', 'log2']
}
grid = GridSearchCV(
    DecisionTreeRegressor(),
    param_grid,
    refit=True,
    verbose=3,
    n_jobs=-1,
)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [7]:
re=grid.cv_results_
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.009526,0.000500,0.004379,0.000303,squared_error,None,best,"{'criterion': 'squared_error', 'max_features':...",0.747746,0.537989,0.755178,0.615584,0.687845,0.668868,0.082462,2
1,0.008951,0.000551,0.004131,0.000258,squared_error,None,random,"{'criterion': 'squared_error', 'max_features':...",0.744037,0.631193,0.639851,0.645722,0.622008,0.656562,0.044466,5
2,0.006512,0.000894,0.003353,0.000349,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.581996,0.515072,0.685828,0.633119,0.447515,0.572706,0.084293,17
3,0.006084,0.000890,0.003626,0.000441,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.587728,0.662406,0.497398,0.611188,0.661884,0.604121,0.060733,14
4,0.006704,0.000687,0.004449,0.000785,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.747121,0.575681,0.739301,0.576050,0.530373,0.633705,0.090975,9
5,0.005125,0.000267,0.003442,0.000301,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.690692,0.595268,0.616402,0.590024,0.641732,0.626824,0.036770,11
6,0.008092,0.001430,0.004195,0.000277,friedman_mse,None,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.724362,0.548598,0.757118,0.637467,0.663202,0.666149,0.072544,3
7,0.006309,0.000843,0.004215,0.000751,friedman_mse,None,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.725633,0.614037,0.730888,0.546368,0.593139,0.642013,0.073770,7
8,0.006692,0.000476,0.003650,0.000179,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.578010,0.648503,0.595219,0.079476,0.627682,0.505778,0.214561,18
9,0.005768,0.000296,0.003881,0.000256,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.722327,0.535731,0.563321,0.540516,0.559432,0.584265,0.069837,16
10,0.006137,0.000394,0.004148,0.000245,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.760047,0.577879,0.651050,0.663652,0.646779,0.659882,0.058346,4
11,0.006470,0.000379,0.003978,0.000376,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.641563,0.560169,0.590795,0.646657,0.584648,0.604766,0.033757,13
12,0.025394,0.001646,0.003697,0.000390,absolute_error,None,best,"{'criterion': 'absolute_error', 'max_features'...",0.758595,0.616549,0.602212,0.539948,0.659423,0.635346,0.072556,8
13,0.019680,0.001153,0.004320,0.000635,absolute_error,None,random,"{'criterion': 'absolute_error', 'max_features'...",0.685912,0.698461,0.647545,0.714455,0.615147,0.672304,0.036128,1
14,0.015139,0.000708,0.003757,0.000317,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.658225,0.586939,0.647391,0.626434,0.558616,0.615521,0.037453,12
15,0.014852,0.001093,0.005240,0.001134,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.668951,0.667326,0.612918,0.579342,0.609108,0.627529,0.035141,10
16,0.018417,0.001350,0.004044,0.000550,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.640878,0.632882,0.692399,0.652069,0.625843,0.648814,0.023472,6
17,0.013757,0.001046,0.004086,0.000296,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.534869,0.667338,0.596635,0.612858,0.550910,0.592522,0.047081,15

In [8]:
y_pred=grid.predict(X_test)

In [9]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test, y_pred)
r_score

0.7301288963001679

In [10]:
age=float(input("Age:"))
bmi=float(input("BMI:"))
children=float(input("Children:"))
sex_male=int(input("Sex Male 0 or 1:"))
smoker_yes=int(input("Smoker Yes 0 or 1:"))

Age: 24
BMI: 34
Children: 2
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 0

In [11]:
y_pred=grid.predict([[age,bmi,children,sex_male,smoker_yes]])
print("Charges",y_pred)

Charges [3500.6123]

C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(