In [1]:
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [2]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [3]:
independent=dataset[["age","bmi","children","sex_male","smoker_yes"]]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [4]:
dependent=dataset[["charges"]]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
X_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]],
      shape=(936, 5))

In [7]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {
    'criterion': ['squared_error', 'poisson', 'absolute_error', 'friedman_mse'],
    'n_estimators': [50, 100, 200],
    'max_features': [None, 'sqrt', 'log2']
}
grid = GridSearchCV(
    RandomForestRegressor(),
    param_grid,
    refit=True,
    verbose=3,
    n_jobs=-1
)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

C:\Anaconda\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'poisson',
                                       'absolute_error', 'friedman_mse'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'n_estimators': [50, 100, 200]},
             verbose=3)

In [8]:
re=grid.cv_results_
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.308201,0.030022,0.012926,0.002241,squared_error,None,50,"{'criterion': 'squared_error', 'max_features':...",0.859570,0.761224,0.815661,0.790405,0.767283,0.798829,0.035925,33
1,0.669192,0.072124,0.023339,0.004278,squared_error,None,100,"{'criterion': 'squared_error', 'max_features':...",0.860216,0.766640,0.818120,0.801327,0.769235,0.803107,0.034546,28
2,1.133623,0.064728,0.039838,0.002991,squared_error,None,200,"{'criterion': 'squared_error', 'max_features':...",0.862263,0.770095,0.819179,0.801877,0.766772,0.804037,0.035114,25
3,0.256978,0.021883,0.014369,0.003227,squared_error,sqrt,50,"{'criterion': 'squared_error', 'max_features':...",0.868317,0.796353,0.812229,0.830723,0.767428,0.815010,0.033789,1
4,0.524301,0.039444,0.024083,0.004496,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.868294,0.789779,0.808510,0.832526,0.763277,0.812478,0.035970,14
5,1.019572,0.080236,0.044231,0.005035,squared_error,sqrt,200,"{'criterion': 'squared_error', 'max_features':...",0.864125,0.795025,0.809748,0.827107,0.771511,0.813503,0.031198,7
6,0.319390,0.056417,0.012207,0.001349,squared_error,log2,50,"{'criterion': 'squared_error', 'max_features':...",0.862799,0.802704,0.803150,0.821274,0.775439,0.813073,0.028852,8
7,0.556820,0.042592,0.019975,0.001198,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.860821,0.792912,0.815224,0.831700,0.768723,0.813876,0.031628,4
8,1.020567,0.087677,0.039367,0.008123,squared_error,log2,200,"{'criterion': 'squared_error', 'max_features':...",0.868746,0.793556,0.809087,0.830198,0.771254,0.814568,0.033248,2
9,0.345981,0.035388,0.014782,0.003480,poisson,None,50,"{'criterion': 'poisson', 'max_features': None,...",0.862114,0.760007,0.810709,0.808910,0.765319,0.801412,0.036998,31
10,0.687958,0.032111,0.025101,0.005009,poisson,None,100,"{'criterion': 'poisson', 'max_features': None,...",0.862377,0.769779,0.814991,0.801267,0.770748,0.803833,0.034096,26
11,1.273108,0.049154,0.041211,0.004831,poisson,None,200,"{'criterion': 'poisson', 'max_features': None,...",0.864514,0.766053,0.815457,0.802618,0.769756,0.803680,0.035798,27
12,0.277298,0.022307,0.012856,0.001680,poisson,sqrt,50,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.867036,0.791435,0.805672,0.829552,0.771181,0.812975,0.033049,9
13,0.549843,0.036996,0.025046,0.006397,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.864161,0.786386,0.809160,0.832344,0.766250,0.811660,0.034326,17
14,1.030388,0.041135,0.038470,0.007579,poisson,sqrt,200,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.863995,0.790212,0.807459,0.830781,0.771114,0.812712,0.032313,12
15,0.294946,0.041400,0.015381,0.004106,poisson,log2,50,"{'criterion': 'poisson', 'max_features': 'log2...",0.860809,0.784165,0.806333,0.830815,0.765496,0.809524,0.033691,22
16,0.539718,0.053235,0.022913,0.005632,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.860721,0.789729,0.810867,0.829430,0.767864,0.811722,0.032007,16
17,1.033849,0.060783,0.036385,0.005708,poisson,log2,200,"{'criterion': 'poisson', 'max_features': 'log2...",0.860073,0.789830,0.808660,0.829369,0.766851,0.810957,0.032088,20
18,1.018758,0.081926,0.011475,0.001980,absolute_error,None,50,"{'criterion': 'absolute_error', 'max_features'...",0.844231,0.772417,0.800994,0.807280,0.767290,0.798442,0.027673,34
19,1.932853,0.133610,0.021440,0.003213,absolute_error,None,100,"{'criterion': 'absolute_error', 'max_features'...",0.850486,0.778996,0.799042,0.797876,0.770256,0.799331,0.027849,32
20,4.076386,0.313504,0.038116,0.006094,absolute_error,None,200,"{'criterion': 'absolute_error', 'max_features'...",0.850951,0.773607,0.799206,0.797583,0.762065,0.796682,0.030604,36
21,0.682129,0.048618,0.015379,0.003039,absolute_error,sqrt,50,"{'criterion': 'absolute_error', 'max_features'...",0.854237,0.786424,0.805456,0.831592,0.768413,0.809224,0.030744,23
22,1.313332,0.134253,0.017621,0.000890,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.862876,0.793878,0.812931,0.830910,0.771389,0.814397,0.031291,3
23,2.413817,0.116939,0.045687,0.013889,absolute_error,sqrt,200,"{'criterion': 'absolute_error', 'max_features'...",0.859545,0.795166,0.811711,0.827743,0.774425,0.813718,0.028945,5
24,0.684893,0.037076,0.012192,0.002031,absolute_error,log2,50,"{'criterion': 'absolute_error', 'max_features'...",0.856071,0.788895,0.810551,0.827068,0.772838,0.811085,0.029103,18
25,1.261238,0.154618,0.019794,0.004352,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.863062,0.793122,0.804701,0.825173,0.766009,0.810413,0.032536,21
26,2.509502,0.139251,0.043560,0.006864,absolute_error,log2,200,"{'criterion': 'absolute_error', 'max_features'...",0.860419,0.796610,0.809271,0.825808,0.772149,0.812851,0.029543,10
27,0.316307,0.031159,0.011630,0.000778,friedman_mse,None,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.863110,0.759501,0.810688,0.795904,0.761250,0.798091,0.038046,35
28,0.610849,0.025078,0.026879,0.003748,friedman_mse,None,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.859860,0.765856,0.814291,0.797630,0.770184,0.801564,0.034163,30
29,1.174822,0.090047,0.040850,0.005639,friedman_mse,None,200,"{'criterion': 'friedman_mse', 'max_features': ...",0.863137,0.762175,0.817695,0.798066,0.770067,0.802228,0.036345,29
30,0.261957,0.025039,0.014441,0.001859,friedman_mse,sqrt,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.858737,0.799252,0.799497,0.830598,0.771949,0.812007,0.029844,15
31,0.480800,0.049824,0.019633,0.001367,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.862909,0.786034,0.809543,0.828192,0.768210,0.810978,0.033005,19
32,0.945766,0.033273,0.039888,0.002929,friedman_mse,sqrt,200,"{'criterion': 'friedman_mse', 'max_features': ...",0.865557,0.790495,0.809520,0.830437,0.767029,0.812608,0.033756,13
33,0.258411,0.036795,0.013289,0.004711,friedman_mse,log2,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.861019,0.789770,0.805238,0.819508,0.760697,0.807247,0.033221,24
34,0.535664,0.036417,0.021346,0.001701,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.861996,0.793594,0.807998,0.830147,0.769847,0.812716,0.031490,11
35,0.801506,0.082789,0.028127,0.001577,friedman_mse,log2,200,"{'criterion': 'friedman_mse', 'max_features': ...",0.866057,0.789434,0.809973,0.828764,0.774203,0.813686,0.032034,6

In [9]:
y_pred=grid.predict(X_test)

In [10]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test, y_pred)
r_score

0.8734722694869448

In [11]:
age=float(input("Age:"))
bmi=float(input("BMI:"))
children=float(input("Children:"))
sex_male=int(input("Sex Male 0 or 1:"))
smoker_yes=int(input("Smoker Yes 0 or 1:"))

Age: 34
BMI: 32
Children: 2
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 2

In [12]:
y_pred=grid.predict([[age,bmi,children,sex_male,smoker_yes]])
print("Charges",y_pred)

Charges [46768.7587586]