In [1]:
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [2]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [3]:
independent=dataset[["age","bmi","children","sex_male","smoker_yes"]]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [4]:
dependent=dataset[["charges"]]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [6]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {
    'criterion': ['squared_error', 'poisson', 'absolute_error', 'friedman_mse'],
    'n_estimators': [50, 100, 200],
    'max_features': [None, 'sqrt', 'log2']
}
grid = GridSearchCV(
    RandomForestRegressor(),
    param_grid,
    refit=True,
    verbose=3,
    n_jobs=-1
)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

C:\Anaconda\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'poisson',
                                       'absolute_error', 'friedman_mse'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'n_estimators': [50, 100, 200]},
             verbose=3)

In [7]:
re=grid.cv_results_
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.311342,0.011679,0.017173,0.001965,squared_error,None,50,"{'criterion': 'squared_error', 'max_features':...",0.864783,0.763315,0.814212,0.795485,0.768167,0.801193,0.036800,29
1,0.625852,0.029767,0.028216,0.003423,squared_error,None,100,"{'criterion': 'squared_error', 'max_features':...",0.861777,0.756571,0.813506,0.791920,0.770890,0.798933,0.036856,32
2,1.174747,0.030736,0.042663,0.008304,squared_error,None,200,"{'criterion': 'squared_error', 'max_features':...",0.862265,0.759894,0.814598,0.803040,0.770310,0.802021,0.036246,28
3,0.301191,0.043954,0.017962,0.005058,squared_error,sqrt,50,"{'criterion': 'squared_error', 'max_features':...",0.865678,0.793089,0.808801,0.829023,0.776553,0.814629,0.030857,1
4,0.515014,0.032491,0.025107,0.003729,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.862311,0.791643,0.805304,0.820433,0.770707,0.810079,0.030816,18
5,0.990446,0.056379,0.046514,0.004280,squared_error,sqrt,200,"{'criterion': 'squared_error', 'max_features':...",0.864444,0.791357,0.805886,0.828373,0.769416,0.811895,0.032543,11
6,0.275084,0.030581,0.017054,0.004107,squared_error,log2,50,"{'criterion': 'squared_error', 'max_features':...",0.858418,0.786955,0.813017,0.829219,0.765109,0.810544,0.032458,17
7,0.526016,0.054223,0.025649,0.003391,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.867274,0.786590,0.809636,0.830668,0.773496,0.813533,0.033244,4
8,0.995775,0.047715,0.042991,0.004133,squared_error,log2,200,"{'criterion': 'squared_error', 'max_features':...",0.866806,0.793147,0.808991,0.831720,0.768467,0.813826,0.033572,2
9,0.360221,0.024202,0.018394,0.004095,poisson,None,50,"{'criterion': 'poisson', 'max_features': None,...",0.853394,0.760251,0.798373,0.794361,0.768299,0.794936,0.032687,36
10,0.730719,0.069720,0.025360,0.001488,poisson,None,100,"{'criterion': 'poisson', 'max_features': None,...",0.863654,0.766640,0.811270,0.802472,0.776110,0.804029,0.034022,26
11,1.456170,0.073335,0.061672,0.008687,poisson,None,200,"{'criterion': 'poisson', 'max_features': None,...",0.866044,0.767691,0.815657,0.802146,0.770082,0.804324,0.035936,25
12,0.277740,0.019830,0.016935,0.002033,poisson,sqrt,50,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.870152,0.793392,0.801589,0.826657,0.770522,0.812462,0.033972,9
13,0.640880,0.045916,0.036151,0.005701,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.857190,0.787763,0.808109,0.831914,0.767900,0.810575,0.031547,16
14,1.126148,0.056021,0.049259,0.006811,poisson,sqrt,200,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.864146,0.792669,0.811564,0.825673,0.770006,0.812812,0.031750,7
15,0.363211,0.052554,0.018257,0.004488,poisson,log2,50,"{'criterion': 'poisson', 'max_features': 'log2...",0.862329,0.776325,0.806684,0.826649,0.768833,0.808164,0.034171,20
16,0.603881,0.077874,0.033548,0.008144,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.861230,0.789850,0.806957,0.831418,0.768640,0.811619,0.032237,12
17,1.209269,0.147891,0.042297,0.005456,poisson,log2,200,"{'criterion': 'poisson', 'max_features': 'log2...",0.864720,0.791461,0.808364,0.826835,0.769921,0.812260,0.032264,10
18,1.112254,0.131752,0.014427,0.002051,absolute_error,None,50,"{'criterion': 'absolute_error', 'max_features'...",0.841902,0.772766,0.799023,0.810024,0.763385,0.797420,0.027951,34
19,1.995551,0.086182,0.024648,0.003773,absolute_error,None,100,"{'criterion': 'absolute_error', 'max_features'...",0.853240,0.775181,0.793328,0.791410,0.765980,0.795828,0.030460,35
20,4.000154,0.098465,0.045966,0.012953,absolute_error,None,200,"{'criterion': 'absolute_error', 'max_features'...",0.847450,0.778740,0.797811,0.796416,0.767727,0.797629,0.027330,33
21,0.659227,0.057740,0.016462,0.003032,absolute_error,sqrt,50,"{'criterion': 'absolute_error', 'max_features'...",0.850692,0.786277,0.814849,0.821915,0.766453,0.808037,0.029193,21
22,1.293805,0.165271,0.025976,0.003357,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.854217,0.793871,0.804342,0.820696,0.774346,0.809494,0.026950,19
23,2.510386,0.159157,0.037036,0.002706,absolute_error,sqrt,200,"{'criterion': 'absolute_error', 'max_features'...",0.861350,0.788912,0.807444,0.824231,0.774343,0.811256,0.030180,13
24,0.761280,0.033526,0.019851,0.006762,absolute_error,log2,50,"{'criterion': 'absolute_error', 'max_features'...",0.860084,0.798557,0.801232,0.814865,0.759424,0.806832,0.032397,22
25,1.242653,0.064717,0.025646,0.002821,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.857448,0.790511,0.814955,0.829326,0.776555,0.813759,0.028556,3
26,2.361755,0.051589,0.047328,0.008097,absolute_error,log2,200,"{'criterion': 'absolute_error', 'max_features'...",0.856785,0.790427,0.806299,0.826932,0.773135,0.810716,0.029082,14
27,0.336686,0.037489,0.015976,0.005145,friedman_mse,None,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.860023,0.768642,0.823007,0.788686,0.765410,0.801154,0.035870,30
28,0.626215,0.049753,0.021760,0.001260,friedman_mse,None,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.865144,0.755437,0.809219,0.796562,0.770864,0.799445,0.037878,31
29,1.280327,0.067982,0.043799,0.001354,friedman_mse,None,200,"{'criterion': 'friedman_mse', 'max_features': ...",0.861964,0.767222,0.817398,0.805951,0.767344,0.803976,0.035325,27
30,0.274772,0.010292,0.018104,0.003197,friedman_mse,sqrt,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.857030,0.776020,0.804605,0.825709,0.768706,0.806414,0.032506,23
31,0.519100,0.011149,0.027344,0.003438,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.865539,0.788204,0.809160,0.831181,0.770947,0.813006,0.033133,5
32,0.996208,0.027827,0.043635,0.004196,friedman_mse,sqrt,200,"{'criterion': 'friedman_mse', 'max_features': ...",0.862439,0.796033,0.808288,0.826605,0.770072,0.812687,0.030925,8
33,0.278128,0.017907,0.016269,0.001980,friedman_mse,log2,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.858529,0.778056,0.801714,0.818877,0.768834,0.805202,0.031945,24
34,0.534691,0.023312,0.027924,0.002760,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.863983,0.783074,0.815541,0.823564,0.766728,0.810578,0.033837,15
35,0.811956,0.071746,0.029931,0.002361,friedman_mse,log2,200,"{'criterion': 'friedman_mse', 'max_features': ...",0.865165,0.791445,0.811751,0.826200,0.770456,0.813003,0.032161,6

In [8]:
y_pred=grid.predict(X_test)

In [9]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test, y_pred)
r_score

0.8672178421493545

In [10]:
age=float(input("Age:"))
bmi=float(input("BMI:"))
children=float(input("Children:"))
sex_male=int(input("Sex Male 0 or 1:"))
smoker_yes=int(input("Smoker Yes 0 or 1:"))

Age: 24
BMI: 32
Children: 2
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1

In [11]:
y_pred=grid.predict([[age,bmi,children,sex_male,smoker_yes]])
print("Charges",y_pred)

Charges [35292.8366736]

C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(