In [1]:
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [2]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [3]:
independent=dataset[["age","bmi","children","sex_male","smoker_yes"]]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [4]:
dependent=dataset[["charges"]]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
X_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]],
      shape=(936, 5))

In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {
    'kernel': ['linear', 'rbf', 'poly'],
    'C': [0.1, 1, 10, 100],
    'gamma': ['scale', 'auto'],
    'epsilon': [0.01, 0.1, 0.5]
}
grid = GridSearchCV(
    SVR(),
    param_grid,
    refit=True,
    verbose=3,
    n_jobs=-1,
    cv=5
)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 72 candidates, totalling 360 fits

C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=5, estimator=SVR(), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 100], 'epsilon': [0.01, 0.1, 0.5],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'rbf', 'poly']},
             verbose=3)

In [22]:
re=grid.cv_results_
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_epsilon,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.097155,0.020791,0.015061,0.000746,0.1,0.01,scale,linear,"{'C': 0.1, 'epsilon': 0.01, 'gamma': 'scale', ...",-0.035814,-0.031006,-0.141298,-0.132783,-0.135715,-0.095323,0.050649,49
1,0.102312,0.002177,0.039845,0.000953,0.1,0.01,scale,rbf,"{'C': 0.1, 'epsilon': 0.01, 'gamma': 'scale', ...",-0.041183,-0.037570,-0.148165,-0.138258,-0.141679,-0.101371,0.050731,70
2,0.073742,0.004625,0.015679,0.001184,0.1,0.01,scale,poly,"{'C': 0.1, 'epsilon': 0.01, 'gamma': 'scale', ...",-0.040657,-0.037017,-0.147481,-0.137460,-0.141090,-0.100741,0.050659,62
3,0.076587,0.005505,0.014996,0.001041,0.1,0.01,auto,linear,"{'C': 0.1, 'epsilon': 0.01, 'gamma': 'auto', '...",-0.035814,-0.031006,-0.141298,-0.132783,-0.135715,-0.095323,0.050649,49
4,0.096817,0.001546,0.040888,0.000688,0.1,0.01,auto,rbf,"{'C': 0.1, 'epsilon': 0.01, 'gamma': 'auto', '...",-0.041184,-0.037569,-0.148166,-0.138257,-0.141679,-0.101371,0.050731,69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,0.094302,0.000467,0.039365,0.000740,100.0,0.50,scale,rbf,"{'C': 100, 'epsilon': 0.5, 'gamma': 'scale', '...",0.301041,0.338754,0.174071,0.217626,0.183421,0.242982,0.065548,22
68,0.080560,0.002911,0.014967,0.000330,100.0,0.50,scale,poly,"{'C': 100, 'epsilon': 0.5, 'gamma': 'scale', '...",0.537120,0.579369,0.471827,0.537969,0.424472,0.510152,0.054958,12
69,0.084128,0.002133,0.013970,0.000859,100.0,0.50,auto,linear,"{'C': 100, 'epsilon': 0.5, 'gamma': 'auto', 'k...",0.584493,0.655817,0.553351,0.576966,0.546834,0.583492,0.038799,5
70,0.088472,0.005993,0.034940,0.005393,100.0,0.50,auto,rbf,"{'C': 100, 'epsilon': 0.5, 'gamma': 'auto', 'k...",0.300573,0.339498,0.173693,0.217976,0.183392,0.243027,0.065741,19
71,0.070782,0.003182,0.014138,0.003646,100.0,0.50,auto,poly,"{'C': 100, 'epsilon': 0.5, 'gamma': 'auto', 'k...",0.540648,0.575038,0.474824,0.535727,0.424635,0.510174,0.053583,9

In [19]:
y_pred=grid.predict(X_test)

In [20]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.6288863764845701

In [23]:
age=float(input("Age:"))
bmi=float(input("BMI:"))
children=float(input("Children:"))
sex_male=int(input("Sex Male 0 or 1:"))
smoker_yes=int(input("Smoker Yes 0 or 1:"))

Age: 25
BMI: 27
Children: 2
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [24]:
y_pred=grid.predict([[age,bmi,children,sex_male,smoker_yes]])
print("Charges",y_pred)

Charges [113749.7817603]